<a href="https://colab.research.google.com/github/FabsRobles/Practica2-IA/blob/main/notebook/Titanic_EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Actividad 1. Comprensión del dominio del dataset.

En esta primera parte se hizo un análisis de los datos que aparecen en nuestro dataset, se identificaron tipos de datos, valores y celdas vacías.

In [2]:
import pandas as pd

url="https://raw.githubusercontent.com/FabsRobles/Practica2-IA/refs/heads/main/train.csv"
df = pd.read_csv(url)

print(df.shape)
df.head()

(891, 12)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

Teniendo la tabla de valores ahora inspeccionamos los tipos de datos con los que contamos, qué contiene cáda columna y sus valores importantes.

### 1. ¿Cuál es el nombre de las columnas?

In [3]:
df.columns.tolist()

['PassengerId',
 'Survived',
 'Pclass',
 'Name',
 'Sex',
 'Age',
 'SibSp',
 'Parch',
 'Ticket',
 'Fare',
 'Cabin',
 'Embarked']

### 2. ¿Qué representa cada columna?

In [8]:
datos={
    'Columna': ['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
    'Descripción': ['Identificador único del pasajero', 'Indica si el pasajero sobrevivió (1) o no (0)', 'Clase del boleto: Primera, Segunda o Tercera0', 'Nombre del pasajero', 'Sexo(male/female)', 'Edad en años', 'Cuántos hermanos o espos@ iban abordo', 'Cuántos padres o hijos iban abordo', 'Número de boleto', 'Lo que pagó por el boleto', 'Número de camarote', 'Puerto donde abordó: C,Q o S'],
    'Tipo de dato': ['Entero', 'Entero', 'Entero', 'Texto', 'Texto', 'Flotante', 'Entero', 'Entero', 'Texto', 'Flotante', 'Texto', 'Texto']
}

df=pd.DataFrame(datos)

df

        Columna                                    Descripción Tipo de dato
0   PassengerId               Identificador único del pasajero       Entero
1      Survived  Indica si el pasajero sobrevivió (1) o no (0)       Entero
2        Pclass  Clase del boleto: Primera, Segunda o Tercera0       Entero
3          Name                            Nombre del pasajero        Texto
4           Sex                              Sexo(male/female)        Texto
5           Age                                   Edad en años     Flotante
6         SibSp          Cuántos hermanos o espos@ iban abordo       Entero
7         Parch             Cuántos padres o hijos iban abordo       Entero
8        Ticket                               Número de boleto        Texto
9          Fare                      Lo que pagó por el boleto     Flotante
10        Cabin                             Número de camarote        Texto
11     Embarked                   Puerto donde abordó: C,Q o S        Texto

### 3. ¿Cuántos datos faltantes hay en cada columna?

In [5]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

### 4. ¿Hay filas repetidas?

In [7]:
df.duplicated().sum()

np.int64(0)

Después de inspeccionar en qué condiciones se encuentra nuestro dataset, respondemos a las siguientes preguntas.

*   ¿Qué representa cada fila?
> Cada fila de nuestro dataset representa a un pasajero del Titanic.

*   ¿La variable objetivo estaría disponible en un escenario real?
> No, ya que la unica forma de saber si alguien sobrevivió es después del hundimiento, no antes.


*   ¿Existen identificadores o variables con fuga de información?
> La variable Survived contiene la información que requerimos para el análisis, sin embargo en un caso real, esa variable solo estará llena después del hundimiento del barco.


*   ¿Qué decisiones podrían afectar de forma desigual a distintos grupos?
> Si un modelo usara las variables Sex, Age, Pclass, podría favorecer o perjudicar a mujeres, niños o personas de clase baja.